### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by Wink-L** [style507/Text-FCG#1]
我在运行train文件时出现了这个错误FileNotFoundError: [Errno 2] No such file or directory: 'nlp_temp_type/mr.inputs.npy'
是项目里没给全文件吗？
这个错误怎么解决鸭

**Comment by style507** [comment]
如果我没猜错应该是配置的时候，你却少了输入文件吧

**Comment by Wink-L** [comment]
那这个文件是怎么生成的呢，还有就是整个程序的运行顺序是什么呀，还有就是我看有很多ipynb文件这些有用吗，跑程序需不需要运行啊。

**Comment by style507** [comment]
那些没什么用了，那些是做测试用的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月8日(周五) 下午3:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [style507/Text-FCG] 缺少文件 (Issue #1)




 
那这个文件是怎么生成的呢，还有就是整个程序的运行顺序是什么呀，还有就是我看有很多ipynb文件这些有用吗，跑程序需不需要运行啊。

**Comment by Wink-L** [comment]
我其他文件都生成了，但是poses_pad.npy文件和pos2vec.npy没有生成。我仔细看了代码，但是没发现怎么生成这个文件。
学长能帮我看一下嘛
poses = np.load(f"{save_path}/{dataset}.poses_pad.npy")
pos2vec = np.load(f"{save_path}/{dataset}.pos2vec.npy")
![U@8~M@ZW$ZEO MPD4}I%E@X](https://github.com/style507/Text-FCG/assets/79886948/867d1d29-8001-426a-81b8-cfedbccc4ef7)

**Comment by Wink-L** [comment]
上边的问题我解决了，现在就是train文件，运行报错RuntimeError: torch.cat(): expected a non-empty list of Tensors
然后我觉得可能是模型没有传参，这个train需要传参嘛，传参的格式是啥样的鸭。

**Comment by style507** [comment]
这个是传参问题，你去网上找个教程都有的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月8日(周五) 晚上10:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [style507/Text-FCG] 缺少文件 (Issue #1)




 
上边的问题我解决了，现在就是train文件，运行报错RuntimeError: torch.cat(): expected a non-empty list of Tensors
 然后我觉得可能是模型没有传参，这个train需要传参嘛，传参的格式是啥样的鸭。

**Comment by Wink-L** [comment]
改了两天了，这个错还是解决不了，您知道是什么错误嘛。train好像传了参数了。传参到底传什么参，能具体说说嘛。
Traceback (most recent call last):
  File "D:\demo\py\item\Text-FCG\train.py", line 116, in <module>
    train_loss, train_acc, _, _ = train_eval("train", train_loader, model, optimizer, loss_func, device)
  File "D:\demo\py\item\Text-FCG\train.py", line 53, in train_eval
    preds = torch.cat(preds).tolist()
RuntimeError: torch.cat(): expected a non-empty list of Tensors
![image](https://github.com/style507/Text-FCG/assets/79886948/a9911438-c41e-4eab-a8b2-05688ec2b0f4)
![image](https://github.com/style507/Text-FCG/assets/79886948/e290393c-f828-4899-ab35-895cf1c5209a)

**Comment by style507** [comment]
细节详见论文哦，不好意思



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月29日(周三) 晚上6:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [style507/Text-FCG] 缺少文件 (Issue #1)




 
我在运行train文件时出现了这个错误FileNotFoundError: [Errno 2] No such file or directory: 'nlp_temp_type/mr.inputs.npy'
 是项目里没给全文件吗？
 这个错误怎么解决鸭

**Comment by sumgao** [comment]
可以加一下联系方式吗，有问题想请教，我的qq，1285993374 @Wink-L

**Comment by L-Yuguo** [comment]
> 我其他文件都生成了，但是poses_pad.npy文件和pos2vec.npy没有生成。我仔细看了代码，但是没发现怎么生成这个文件。 学长能帮我看一下嘛 poses = np.load(f"{save_path}/{dataset}.poses_pad.npy") pos2vec = np.load(f"{save_path}/{dataset}.pos2vec.npy") 

你好，请问这个问题是怎么解决的呢？

**Comment by SSQSWJ** [comment]
> > 我其他文件都生成了，但是poses_pad.npy文件和pos2vec.npy没有生成。我仔细看了代码，但是没发现怎么生成这个文件。 学长能帮我看一下嘛 poses = np.load(f"{save_path}/{dataset}.poses_pad.npy") pos2vec = np.load(f"{save_path}/{dataset}.pos2vec.npy")
> 
> 你好，请问这个问题是怎么解决的呢？
您好，这两个文件的问题如何解决呢？

**Comment by Shallow001** [comment]
> > > 我其他文件都生成了，但是poses_pad.npy文件和pos2vec.npy没有生成。我仔细看了代码，但是没发现怎么生成这个文件。学长能帮我看一下嘛 poses = np.load（f“{save_path}/{dataset}.poses_pad.npy”） pos2vec = np.load（f“{save_path}/{dataset}.pos2vec.npy”）
> > 
> > 
> > 你好，请问这个问题是怎么解决的呢？
> > 您好，这两个文件的问题如何解决呢？

您解决这个问题了吗

**Comment by Shallow001** [comment]
> 我其他文件都生成了，但是poses_pad.npy文件和pos2vec.npy没有生成。我仔细看了代码，但是没发现怎么生成这个文件。 学长能帮我看一下嘛 poses = np.load（f“{save_path}/{dataset}.poses_pad.npy”） pos2vec = np.load（f“{save_path}/{dataset}.pos2vec.npy”） ![U@8~M@ZW$ZEO MPD4}I%E@X](https://private-user-images.githubusercontent.com/79886948/289055950-867d1d29-8001-426a-81b8-cfedbccc4ef7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTUzMDYsIm5iZiI6MTcyNzI1NTAwNiwicGF0aCI6Ii83OTg4Njk0OC8yODkwNTU5NTAtODY3ZDFkMjktODAwMS00MjZhLTgxYjgtY2ZlZGJjY2M0ZWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA5MDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MzczNmNmNTY1MmE3NmJmMzFlMmU5ZTYyYmI0OTU0MjgwNTAxMGUzNDcwZDUwYWE2MGQ0NjZmMjMzMjcxMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iXTdeNVYThQLr60wu6VCiSxoiQ_LY-WCMDi2q3lZX1E)

请问一下这个问题您是怎么解决的
