### ISSUE TITLE
I catch an issue with loss.backward()

### ISSUE THREAD

**Issue by elitonperin** [style507/Text-FCG#2]
I was trying to train the model with these parameters:
  dataset = "mr"
  save_path = "temp"

  .# params
  batch_size = 128  
  mini_batch_size = 64  
  lr = 0.0003
  dropout = 0.5
  weight_decay = 0.000005
  in_dim = 300
  hid_dim = 128
  freeze = True
  step = 2
  start = 0

And I got this:
Traceback (most recent call last):
  File "train.py", line 77, in <module>
    (train_loader, test_loader, valid_loader), word2vec, pos2vec = get_data_loader(
  File "train.py", line 45, in train_eval
    loss.backward()
  File "/.../anaconda3/envs/tor.12/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/.../anaconda3/envs/tor.12/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1337, 128]], which is output 0 of ReluBackward0, is at version 4;  expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True)

my torch versions:
torch                         1.12.1
torch-geometric               2.1.0
torch-scatter                 2.0.9
torch-sparse                  0.6.15+pt112cu113
torchaudio                    0.12.1
torchvision                   0.13.1

Do you have any idea about this error?

**Comment by Boomerrr** [comment]
将 film_conv.py 中的代码行：
out += self.propagate(edge_index[:, mask], x=lin(x[0]), beta=beta, gamma=gamma, size=None)
修改为：
out = out + self.propagate(edge_index[:, mask], x=lin(x[0]), beta=beta, gamma=gamma, size=None)
相当于将原地操作 += 改为非原地操作 = +。
